
### Create a new song
POST http://localhost:8080/api/v1/song
Content-Type: application/json

{
   "title": "Shape of You",
    "artist": "Ed Sheeran",
    "duration": 240,
    "header_image_url": "https://example.com/image.jpg",
    "url": "https://example.com/song.mp3",
    "release_song_date": "2023-01-01T00:00:00Z",
    "is_active": true
}

### List all songs
GET http://localhost:8080/api/v1/songs
Accept: application/json

### Get a song by ID
GET http://localhost:8080/api/v1/song/0bebc3ba-cf46-480d-8bc1-b22c1a74d7f9
Accept: application/json

### Update a song
PUT http://localhost:8080/api/v1/song/0bebc3ba-cf46-480d-8bc1-b22c1a74d7f9
Content-Type: application/json

{
    "title": "Shape of You (Remix)",
    "artist": "Ed Sheeran",
    "duration": 250,
    "is_active": true
}

### Delete a song
DELETE http://localhost:8080/api/v1/song/0bebc3ba-cf46-480d-8bc1-b22c1a74d7f9
Accept: application/json
